/*
 * Site Bay
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.Region;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegionApi
 */
@Ignore
public class RegionApiTest {

    private final RegionApi api = new RegionApi();

    
    /**
     * Get a Region
     *
     * Get details of a region by its ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRegionTest() throws ApiException {
        Integer regionId = null;
                Region response = api.getRegion(regionId);
        // TODO: test validations
    }
    
    /**
     * Get Regions
     *
     * Get details of all regions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRegionsTest() throws ApiException {
                List<Region> response = api.getRegions();
        // TODO: test validations
    }
    
}
