"""
    Site Bay

    OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.template_api import TemplateApi  # noqa: E501


class TestTemplateApi(unittest.TestCase):
    """TemplateApi unit test stubs"""

    def setUp(self):
        self.api = TemplateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_template(self):
        """Test case for get_template

        Get Templates  # noqa: E501
        """
        pass

    def test_get_templates(self):
        """Test case for get_templates

        Get Templates  # noqa: E501
        """
        pass

    def test_submit_template(self):
        """Test case for submit_template

        Create Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
