"""
    Site Bay

    OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ticket_reply import TicketReply


class TestTicketReply(unittest.TestCase):
    """TicketReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketReply(self):
        """Test TicketReply"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TicketReply()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
