"""
    Site Bay

    OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.plan_api import PlanApi  # noqa: E501


class TestPlanApi(unittest.TestCase):
    """PlanApi unit test stubs"""

    def setUp(self):
        self.api = PlanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_plan(self):
        """Test case for cancel_plan

        Cancel Plan  # noqa: E501
        """
        pass

    def test_create_plan(self):
        """Test case for create_plan

        Create a Plan  # noqa: E501
        """
        pass

    def test_get_plan(self):
        """Test case for get_plan

        Get Plan  # noqa: E501
        """
        pass

    def test_get_plans(self):
        """Test case for get_plans

        Get Plans  # noqa: E501
        """
        pass

    def test_preview_change(self):
        """Test case for preview_change

        Preview Plan  # noqa: E501
        """
        pass

    def test_uncancel_plan(self):
        """Test case for uncancel_plan

        Uncancel Plan  # noqa: E501
        """
        pass

    def test_update_plan(self):
        """Test case for update_plan

        Update a Plan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
