/*
 * Site Bay
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserEmailUpdate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-06T15:29:58.049226-06:00[America/Boise]")
public class UserEmailUpdate {
  public static final String SERIALIZED_NAME_IS_CATCHALL = "is_catchall";
  @SerializedName(SERIALIZED_NAME_IS_CATCHALL)
  private Boolean isCatchall;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public UserEmailUpdate() { 
  }

  public UserEmailUpdate isCatchall(Boolean isCatchall) {
    
    this.isCatchall = isCatchall;
    return this;
  }

   /**
   * Get isCatchall
   * @return isCatchall
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsCatchall() {
    return isCatchall;
  }


  public void setIsCatchall(Boolean isCatchall) {
    this.isCatchall = isCatchall;
  }


  public UserEmailUpdate password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEmailUpdate userEmailUpdate = (UserEmailUpdate) o;
    return Objects.equals(this.isCatchall, userEmailUpdate.isCatchall) &&
        Objects.equals(this.password, userEmailUpdate.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isCatchall, password);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEmailUpdate {\n");
    sb.append("    isCatchall: ").append(toIndentedString(isCatchall)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

