/**
 * Site Bay
 *
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param currentUrl 
 * @param wordpressPassword 
 * @param wordpressUser 
 * @param extra 
 * @param ftpAddress 
 * @param ftpPassword 
 * @param ftpUser 
 * @param host 
 * @param hostPassword 
 * @param hostUser 
 * @param migrationType 
 * @param zipFileName 
 */

data class Migration (

    @Json(name = "current_url")
    val currentUrl: kotlin.String,

    @Json(name = "wordpress_password")
    val wordpressPassword: kotlin.String,

    @Json(name = "wordpress_user")
    val wordpressUser: kotlin.String,

    @Json(name = "extra")
    val extra: kotlin.String? = null,

    @Json(name = "ftp_address")
    val ftpAddress: kotlin.String? = null,

    @Json(name = "ftp_password")
    val ftpPassword: kotlin.String? = null,

    @Json(name = "ftp_user")
    val ftpUser: kotlin.String? = null,

    @Json(name = "host")
    val host: kotlin.String? = null,

    @Json(name = "host_password")
    val hostPassword: kotlin.String? = null,

    @Json(name = "host_user")
    val hostUser: kotlin.String? = null,

    @Json(name = "migration_type")
    val migrationType: kotlin.String? = null,

    @Json(name = "zip_file_name")
    val zipFileName: kotlin.String? = null

)

