/*
Site Bay

OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TemplateCreate struct for TemplateCreate
type TemplateCreate struct {
	FullDescription string `json:"full_description"`
	Name string `json:"name"`
	Plugins string `json:"plugins"`
	Quickstart string `json:"quickstart"`
	ShortDescription string `json:"short_description"`
	Tag string `json:"tag"`
	WpressUrl string `json:"wpress_url"`
}

// NewTemplateCreate instantiates a new TemplateCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateCreate(fullDescription string, name string, plugins string, quickstart string, shortDescription string, tag string, wpressUrl string) *TemplateCreate {
	this := TemplateCreate{}
	this.FullDescription = fullDescription
	this.Name = name
	this.Plugins = plugins
	this.Quickstart = quickstart
	this.ShortDescription = shortDescription
	this.Tag = tag
	this.WpressUrl = wpressUrl
	return &this
}

// NewTemplateCreateWithDefaults instantiates a new TemplateCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateCreateWithDefaults() *TemplateCreate {
	this := TemplateCreate{}
	return &this
}

// GetFullDescription returns the FullDescription field value
func (o *TemplateCreate) GetFullDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullDescription
}

// GetFullDescriptionOk returns a tuple with the FullDescription field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetFullDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FullDescription, true
}

// SetFullDescription sets field value
func (o *TemplateCreate) SetFullDescription(v string) {
	o.FullDescription = v
}

// GetName returns the Name field value
func (o *TemplateCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateCreate) SetName(v string) {
	o.Name = v
}

// GetPlugins returns the Plugins field value
func (o *TemplateCreate) GetPlugins() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetPluginsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Plugins, true
}

// SetPlugins sets field value
func (o *TemplateCreate) SetPlugins(v string) {
	o.Plugins = v
}

// GetQuickstart returns the Quickstart field value
func (o *TemplateCreate) GetQuickstart() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quickstart
}

// GetQuickstartOk returns a tuple with the Quickstart field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetQuickstartOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quickstart, true
}

// SetQuickstart sets field value
func (o *TemplateCreate) SetQuickstart(v string) {
	o.Quickstart = v
}

// GetShortDescription returns the ShortDescription field value
func (o *TemplateCreate) GetShortDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShortDescription
}

// GetShortDescriptionOk returns a tuple with the ShortDescription field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetShortDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShortDescription, true
}

// SetShortDescription sets field value
func (o *TemplateCreate) SetShortDescription(v string) {
	o.ShortDescription = v
}

// GetTag returns the Tag field value
func (o *TemplateCreate) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetTagOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *TemplateCreate) SetTag(v string) {
	o.Tag = v
}

// GetWpressUrl returns the WpressUrl field value
func (o *TemplateCreate) GetWpressUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WpressUrl
}

// GetWpressUrlOk returns a tuple with the WpressUrl field value
// and a boolean to check if the value has been set.
func (o *TemplateCreate) GetWpressUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WpressUrl, true
}

// SetWpressUrl sets field value
func (o *TemplateCreate) SetWpressUrl(v string) {
	o.WpressUrl = v
}

func (o TemplateCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["full_description"] = o.FullDescription
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["plugins"] = o.Plugins
	}
	if true {
		toSerialize["quickstart"] = o.Quickstart
	}
	if true {
		toSerialize["short_description"] = o.ShortDescription
	}
	if true {
		toSerialize["tag"] = o.Tag
	}
	if true {
		toSerialize["wpress_url"] = o.WpressUrl
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateCreate struct {
	value *TemplateCreate
	isSet bool
}

func (v NullableTemplateCreate) Get() *TemplateCreate {
	return v.value
}

func (v *NullableTemplateCreate) Set(val *TemplateCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateCreate(val *TemplateCreate) *NullableTemplateCreate {
	return &NullableTemplateCreate{value: val, isSet: true}
}

func (v NullableTemplateCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


