/*
 * Site Bay
 *
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ExternalPathCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalPathCreateTests
    {
        // TODO uncomment below to declare an instance variable for ExternalPathCreate
        //private ExternalPathCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalPathCreate
            //instance = new ExternalPathCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalPathCreate
        /// </summary>
        [Test]
        public void ExternalPathCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ExternalPathCreate
            //Assert.IsInstanceOf(typeof(ExternalPathCreate), instance);
        }


        /// <summary>
        /// Test the property 'ExternalName'
        /// </summary>
        [Test]
        public void ExternalNameTest()
        {
            // TODO unit test for the property 'ExternalName'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
