/*
 * Site Bay
 *
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TemplateCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateCreateTests
    {
        // TODO uncomment below to declare an instance variable for TemplateCreate
        //private TemplateCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplateCreate
            //instance = new TemplateCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateCreate
        /// </summary>
        [Test]
        public void TemplateCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TemplateCreate
            //Assert.IsInstanceOf(typeof(TemplateCreate), instance);
        }


        /// <summary>
        /// Test the property 'FullDescription'
        /// </summary>
        [Test]
        public void FullDescriptionTest()
        {
            // TODO unit test for the property 'FullDescription'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Plugins'
        /// </summary>
        [Test]
        public void PluginsTest()
        {
            // TODO unit test for the property 'Plugins'
        }
        /// <summary>
        /// Test the property 'Quickstart'
        /// </summary>
        [Test]
        public void QuickstartTest()
        {
            // TODO unit test for the property 'Quickstart'
        }
        /// <summary>
        /// Test the property 'ShortDescription'
        /// </summary>
        [Test]
        public void ShortDescriptionTest()
        {
            // TODO unit test for the property 'ShortDescription'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'WpressUrl'
        /// </summary>
        [Test]
        public void WpressUrlTest()
        {
            // TODO unit test for the property 'WpressUrl'
        }

    }

}
