/*
 * Site Bay
 *
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TicketReplyCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TicketReplyCreateTests
    {
        // TODO uncomment below to declare an instance variable for TicketReplyCreate
        //private TicketReplyCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TicketReplyCreate
            //instance = new TicketReplyCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TicketReplyCreate
        /// </summary>
        [Test]
        public void TicketReplyCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TicketReplyCreate
            //Assert.IsInstanceOf(typeof(TicketReplyCreate), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Resolve'
        /// </summary>
        [Test]
        public void ResolveTest()
        {
            // TODO unit test for the property 'Resolve'
        }

    }

}
