/**
 * Site Bay
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SiteLiveCreate { 
    fqdn: string;
    git_url?: string;
    region_id?: number;
    team_id: string;
    template_name?: string;
    wordpressBlogName: string;
    wordpressEmail: string;
    wordpressFirstName: string;
    wordpressLastName: string;
    wordpressPassword: string;
    wordpressUsername: string;
}

