/*
 * Site Bay
 * OpenAPI schema for the Agency plan. Access for only $99USD per month! Swagger docs available at https://my.sitebay.org/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TicketCreate
 */
public class TicketCreateTest {
    private final TicketCreate model = new TicketCreate();

    /**
     * Model tests for TicketCreate
     */
    @Test
    public void testTicketCreate() {
        // TODO: test TicketCreate
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'resolved'
     */
    @Test
    public void resolvedTest() {
        // TODO: test resolved
    }

    /**
     * Test the property 's3Object'
     */
    @Test
    public void s3ObjectTest() {
        // TODO: test s3Object
    }

    /**
     * Test the property 'siteLiveId'
     */
    @Test
    public void siteLiveIdTest() {
        // TODO: test siteLiveId
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

}
